config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: :sessions
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  resources :tweets,only: [:new,:show] 
  resources :companys,only: [:index,:new,:show,:create,:edit,:update,:destroy] do
    resources :messages, only: [:create]
    resources :consultations, only: [:index,:new,:show,:create,:edit,:update,:destroy]
  end
  resources :users, only: [:show, :index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :users, through: :chat_room_users
  has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :names
  has_many :consultations
  mount_uploader :profile_image, CompanyProfileImageUploader

  with_options presence: true do
  validates :name
  validates :introduce
 end
end

app/models/consultation.rb
class Consultation < ApplicationRecord
belongs_to :user
belongs_to :company

with_options presence: true do
  validates :name
  validates :name
end
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user
belongs_to :company

  validates :text, presence: true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"

  enum status: { like: 0, dislike: 1 }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  
 

  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :reactions
  has_many :consultations
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  
  enum gender: { man: 0, woman: 1 }
  validates :self_introduction, length: { maximum: 500 }
  mount_uploader :profile_image, ProfileImageUploader

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @esers = User.new
  end

  def index
    @users = User.where.not(id: current_user.id)
    @user = User.find(current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hikari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <meta name="viewport" content="width=device-width, initial-scale=1">

     
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-light">
 <%= link_to users_path, class: "nav-item nav-link", data: { turbolinks: :false } do %>
    <span class="<%= 'active' if current_page?(users_path) %>">
      <i class="fas fa-fire fa-lg inherit"></i>
    </span>
  <% end %>

  <%= link_to matching_index_path, class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(matching_index_path) %>">
      <i class="fas fa-comments fa-lg inherit"></i>
    </span>
  <% end %>

  

</nav>