config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: :sessions
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  resources :tweets,only: [:new,:show] 
  resources :companys,only: [:index,:new,:show,:create,:edit,:update,:destroy] do
    resources :messages, only: [:create]
    resources :consultations, only: [:index,:new,:show,:create,:edit,:update,:destroy]
  end
  resources :users, only: [:show, :index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :users, through: :chat_room_users
  has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :names
  has_many :consultations
  mount_uploader :profile_image, CompanyProfileImageUploader

  with_options presence: true do
  validates :name
  validates :introduce
 end
end

app/models/consultation.rb
class Consultation < ApplicationRecord
belongs_to :user
belongs_to :company

with_options presence: true do
  validates :name
  validates :name
end
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user
belongs_to :company

  validates :text, presence: true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"

  enum status: { like: 0, dislike: 1 }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  
 

  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :reactions
  has_many :consultations
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  
  enum gender: { man: 0, woman: 1 }
  validates :self_introduction, length: { maximum: 500 }
  mount_uploader :profile_image, ProfileImageUploader

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end


end

app/controllers/companys_controller.rb
class CompanysController < ApplicationController
  def index
    @companys = Company.all
  end

  def new
    @company = Company.new
  end

  def show
    @company = Company.find(params[:id])
    @companys = Company.new
    @messages = Message.all
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companys_path
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])

  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companys_path(@company)
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])
    # if current_user.id == @company.id
    @company.destroy
    redirect_to companys_path
    end
  # end

  private
  def company_params
    params.require(:company).permit(:name, :introduce,:profile_image)
  end

  
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  before_action :authenticate_user!

  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id)
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
    @user = User.find(current_user.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
  end

  def new
  end

  def show
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @esers = User.new
  end

  def index
    @users = User.where.not(id: current_user.id)
    @user = User.find(current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companys/edit.html.erb
<div class="user-edit-page">

  <%# <%= render "partial/navbar" %> 

  <%= form_with model: @company, url: company_path(@company), class: "px-3", local: true, method: :patch do |f| %>
    <%# <%= render "devise/shared/error_messages", resource: resource %> 

    <div class="profile">
    <img id="profile-img-prev" src="#" class='hidden' />
    <% if @company.profile_image.url.nil? %>
      <div class="profile-default-img"></div>
    <% else %>
      <%= image_tag @company.profile_image.url, class: "profile-img", id: "profile-img" %>
    <% end %>

    <label class="profile-img-upload">
      <%= f.file_field :profile_image, id: "profile_image_upload" %>ファイルを選択
    </label>
  </div>

    <div class="form-group">
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "メールアドレス" %>
    </div>

    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "名前" %>
    </div>

  
    <div class="form-group">
      <%= f.text_area :introduce, class: "form-control", placeholder: "紹介", rows: "4" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control", placeholder: "パスワード" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", placeholder: "パスワードの確認" %>
    </div>

    <div class="user-edit__submit-btn">
      <%= f.submit "保存", class: "btn btn-block text-white" %>
    </div>
  <% end %>

</div>

app/views/companys/index.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>アルバムサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
<%= link_to "会社新規登録",new_company_path %>
    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">撮影者や撮影した背景など、アルバムに関する情報を追加しましょう。いくつかの文を書いておくと、友達が写真を選ぶ手助けになるかもしれません。また、写真は SNS や連絡先へとリンクしておきましょう。</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Twitter でフォローする</a></li>
            <li><a href="#" class="text-white">Facebook でいいねする</a></li>
            <li><a href="#" class="text-white">Email を送る</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>アルバム</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <%# <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">アルバムページのサンプル</h1>
        <p class="lead text-muted">内容や作成者など、以下のコレクションに関する簡単な説明文を書きましょう。なるべく短く、わかりやすい文にしましょう。しかし短すぎると、友達は見てくれないかもしれません。</p>
        <p>
          <a href="#" class="btn btn-primary my-2">メインアクション</a>
          <a href="#" class="btn btn-secondary my-2">サブアクション</a>
        </p>
      </div>
    </div>
  </section> %>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @companys.reverse_each do |company|%>
        <div class="col">
          <div class="card shadow-sm">
            <% if company.profile_image.url.nil? %>
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <% else %>
              <%= image_tag company.profile_image.url, class: "profile-img card-img-top" %>
            <% end %>

            <div class="card-body">


              <p class="card-text"><%=  company.name  %></p>
              <p class="card-text"><%=  company.introduce  %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                   <ul>
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">見る</button> %>
                  <li><%= link_to "見る",company_path(company.id) %></li>
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">削除</button> %>
                  <li><%= link_to "削除",company_path(company.id),method: :delete %></li>
                  </ul>
                </div>
                <small class="text-muted">9分</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>


 
        
      </div>
    </div>
  </div>


</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="/">トップに戻る</a>
    </p>
    <p class="mb-1">アルバムサンプルは &copy; Bootstrap ですが、ダウンロードしてカスタマイズしてみましょう。</p>
    <p class="mb-0">Bootstrap は初めてですか？ <a href="/">Bootstrap ホームページにアクセスする</a>か<a href="/docs/5.0/getting-started/introduction/">スタートガイド</a>を読みましょう。</p>
  </div>
</footer>


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

      
  </body>



</html>

app/views/companys/new.html.erb
<div class="sign-up-page">
  <div class="card">
    <div class="card-header">
      アカウントを作成する
    </div>

    <div class="card-body">
      <%= form_with model: @company, url: companys_path, local: true do |f| %>
       <div class="profile">
       <img id="profile-img-prev" src="#" class='hidden' />
         <% if @company.profile_image.url.nil? %>
          <div class="profile-default-img"></div>
          <% else %>
          <%= image_tag @company.profile_image.url, class: "profile-img", id: "profile-img" %>
          <% end %>
          <label class="profile-img-upload">
          <%= f.file_field :profile_image, id: "profile_image_upload" %>ファイルを選択
          </label>
        </div>
        <div class="form-group">
          <%= f.text_field :name, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "メールアドレス" %>
        </div>

        <div class="form-group">
          <%= f.text_area :introduce, class: "form-control", placeholder: "名前" %>
        </div>

        <div class="sign-up__submit-btn">
          <%= f.submit "参加する", class: "btn btn-block text-white" %>
        </div>
        <% end %>
      </div>
    </div>



  <%# <%= link_to "#", class: "nav-item nav-link" do %>
    <%# <i class="fas fa-comments fa-lg inherit"></i>
  <% end %> 
  <%# <%= link_to user_path(@user), class: "nav-item nav-link" do %> 
    <%# <span class="<%= 'active' if current_page?(user_path(@user)) || current_page?(edit_user_registration_path) %>
      <%# <i class="fas fa-user fa-lg inherit"></i>
    </span>
    <% end %> 
 

app/views/companys/show.html.erb
<div class="user-show-page">
  <div class="container">
    <nav class="navbar navbar-dark ">
     <div class = "home text-left">
      <%= link_to "COMPANY",root_path ,class: "navbar-brand text-dark" %>
     </div>
   </nav>
  </div>
  
  <%= render "partial/navbar" %>

  <div class="profile mt-4">
    <% if @company.profile_image.url.nil? %>
      <div class="profile-default-img"></div>
    <% else %>
      <%= image_tag @company.profile_image.url, class: "profile-img" %>
    <% end %>
  </div>

  <%= form_with model:@companys, url: companys_path,class: "px-3", local: true do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder:@company.name  %>
    </div>
    <div class="form-group">
      <%= f.text_area :introduce, class: "form-control", placeholder: @company.introduce, rows: "4" %>
    </div>


    <% if current_user.id == @company.id %>
      <div class="user-action">
        <div class="user-action-common">
          <%= link_to "ログアウト",company_path(@company), method: :delete do %>
            <i class="fas fa-sign-out-alt fa-2x"></i>
          <% end %>
        </div>
        <div class="user-action-common">
          <%= link_to "情報を編集",edit_company_path(@company) do %>
            <i class="fas fa-pencil-alt fa-2x"></i>
          <% end %>
        </div>
        <% else %>
        <%= link_to "相談する",new_company_consultation_path(@company)  %>
      </div>
    <% end %>
    <% end %>

app/views/tweets/index.html.erb
<div class="jumbotron">
  <div class="container">
    <nav class="navbar navbar-light">
      <a class="navbar-brand text-white">COMPANY</a>
      <div class="navbar__sign-in-btn">
    <%= link_to "ログイン", new_user_session_path, class: "btn my-2 my-sm-0 bg-light text-top-color" %>
      </div>
    </nav>
  </div>

  <div class="top-title">
    <h4 class="text-white text-center">Best Job</h4><br>
    <p>最高のビジネスパートナーをマッチングするアプリ</p>
  </div>

  <div class="top-authentication text-center">
    <div class="top-authentication__sign-up-btn m-3">
      <%= link_to "アカウントを作成する", "#", class: "btn text-white" %>
    </div>
    <div class="top-authentication__sign-in-btn m-3">
      <%= link_to "ログイン", "#", class: "btn text-white" %>
    </div>
</div>

app/views/tweets/new.html.erb
<div class = "home text-left">
<%= link_to "COMPANY",root_path ,class: "navbar-brand text-black" %>
</div>
<!doctype html>

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.2/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">About us</h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Contact</a>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">自由に転職ができる世界</h1>

    <p class="lead">現在本当の意味で仕事を心から楽しんでしている方は一体どのくらいの割合なのだろうか？そういった方達は毎日が非常に充実していて心から尊敬できるし素晴らしいと思います。</p>
    <p>しかし、その反面「もう歳だから今から転職は無理がある」「今の会社は辛いけど転職するのは生活が変わってしまうから怖い」「やってみたいことはあるが今より状況が悪くなったらどうしよう」などいろんな不満を抱えながら仕事をしている方達も非常に数多く存在することと思う。</p>
    <p>このアプリケーションではそういった思いのあるユーザーと、「今まで」ではなく「今とこれから」を尊重してくださる企業をマッチングアプリを通じて是非今後の人生の転機としてご活用いただけるよう開発させていただきました。</p>
    <p>たった一度しかない人生だからこそ悔いがない仕事選びができますよう心から応援しております。</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
    </p>
  </main>


</div>
</body>
  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
  </footer>
</html>

app/views/tweets/serch.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= link_to "COMPANY",root_path ,class: "navbar-brand text-black" %>
<div class="user-index-page">
  <%= render "partial/navbar" %>
  

  <div class="swipe">
    <div class="swipe--status">
      <i class="fa fa-times"></i>
      <i class="fa fa-heart"></i>
    </div>

    <div class="swipe--cards">
      <% @users.each do |user| %>
        <div class="swipe--card" id="<%= user.id %>">
          <% if user.profile_image.url.nil? %>
            <div class="profile-default-img"></div>
          <% else %>
            <%= image_tag user.profile_image.url, class: "profile-img" %>
          <% end %>
          <p class="profile-name">
            <%= user.name %>
          </p>
        </div>
      <% end %>
      <div class="no-user">近くにお相手がいません</div>
    </div>

    <div class="swipe--buttons">
      <button id="dislike"><i class="fas fa-times fa-2x"></i></button>
      <button id="like"><i class="fas fa-heart fa-2x"></i></button>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="user-show-page">

  <%= render "partial/navbar" %>
  <div class="profile mt-4">
    <% if @user.profile_image.url.nil? %>
      <div class="profile-default-img"></div>
    <% else %>
      <%= image_tag @user.profile_image.url, class: "profile-img" %>
    <% end %>
  </div>
  <%= form_with model:@users, class: "px-3", local: true do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder:@user.name  %>
    </div>
    <div class="form-group">
      <%= f.text_area :self_introduction, class: "form-control", placeholder: @user.self_introduction, rows: "4" %>
    </div>
  <% end %>



  <% if current_user.id == @user.id %>
    <div class="user-action">
      <div class="user-action-common">
       <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt fa-2x"></i>
        <% end %>
        <span>ログアウト</span>
      </div>
      <div class="user-action-common">
        <%= link_to edit_user_registration_path do %>
          <i class="fas fa-pencil-alt fa-2x"></i>
        <% end %>
        <span>情報を編集<span>
      </div>
    </div>
   
  <% end %>
  

</div>